name: E2E Tests

on:
  push:
    tags:
      - 'test'

jobs:
  build-and-test:
    timeout-minutes: 60
    runs-on: windows-latest

    steps:
      - name: Receiving the code
        uses: actions/checkout@v4

      - name: Installing Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Installing Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Installing Node modules
        run: npm install

      - name: Installing Python dependencies
        run: |
          pip install -r src/scripts/python/requirements.txt

      - name: Installing browsers for Playwright
        run: npx playwright install --with-deps chromium

      - name: Building Vite (Frontend)
        run: npm run vite:build

      - name: Building C#
        run: npm run C#:build

      - name: Building Python
        run: npm run py:build

      - name: Run Playwright tests
        run: npx playwright test --retries=2
        env:
          CI: true
