name: Build and Release Sonata

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Installing Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Installing Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Installing Node modules
        run: npm install

      - name: Installing Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller numpy openpyxl python-docx lxml pillow pywin32

      - name: Build and Publish Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run app:publish